python3 lzw.py cantrbry/alice29.txt
python3 lzw.py cantrbry/asyoulik.txt
python3 lzw.py cantrbry/fields.c
python3 lzw.py cantrbry/grammar.lsp
python3 lzw.py cantrbry/kennedy.xls
python3 lzw.py cantrbry/plrabn12.txt
python3 lzw.py cantrbry/ptt5
python3 lzw.py cantrbry/sum
python3 lzw.py cantrbry/xargs.1
python3 lzw.py cantrbry/lxet10.txt